################################################
#                 REST CLIENT                  #
################################################

### Get all users
GET http://localhost:3333/users HTTP/1.1
Authorization: Beaer 

### Register a new user
POST http://localhost:3333/auth/register HTTP/1.1
content-type: application/json

{
  "name": "Ky Phan 4",
  "email": "kyphan4@gmail.com",
  "password": "123456"
}

### Login
POST http://localhost:3333/auth/login HTTP/1.1
content-type: application/json

{
  "email": "kyphan2@gmail.com",
  "password": "123456"
}

### Get user by ID
GET http://localhost:3333/users/3 HTTP/1.1

### Update user by ID
PATCH http://localhost:3333/users/4 HTTP/1.1
content-type: application/json

{
  "name": "Ky Phan 2",
  "email": "kyphan2@gmail.com"
}

### Delete user by ID
PATCH http://localhost:3333/users/delete/5 HTTP/1.1

### Remove user by ID
DELETE http://localhost:3333/users/delete/5 HTTP/1.1